name: Deploy to AWS Lambda

on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Dotnet
              uses: actions/setup-dotnet@v3
              with: 
                dotnet-version: '8.0.x'

            - name: Install AWS CLI
              run: |
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install --update

            - name: AWS Login
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2
            
            - name: Login AWS ECR
              id: login-ecr
              run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 602681090358.dkr.ecr.us-east-2.amazonaws.com

            - name: Build .NET Project
              run: dotnet build --configuration Release -o ./output

            - name: Publish Project
              run: dotnet publish -c Release -o ./output

            - name: Build Docker Image
              run: |
                docker build -t my-lambda-function .
                docker tag my-lambda-function:latest 602681090358.dkr.ecr.us-east-2.amazonaws.com/my-lambda-function:latest

            - name: Push Docker to ECR
              run: |
                docker push 602681090358.dkr.ecr.us-east-2.amazonaws.com/myecr-repo:latest

            - name: Update AWS Lambda Function
              run: |
                aws lambda update-function-code --function-name my-dotnet-lambda \  
                    --image-uri 602681090358.dkr.ecr.us-east-2.amazonaws.com/myecr-repo:latest
